CREATE TABLE IF NOT EXISTS USER_DB (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), last_name VARCHAR(255), email VARCHAR(255), password VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS WALLET_DB (id INT NOT NULL AUTO_INCREMENT, nickname VARCHAR(255), amount INT, userId INT, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS TRANSACTION_DB (id INT NOT NULL AUTO_INCREMENT, origin_wallet_id INT, target_wallet_id INT, amount LONG, created_at DATETIME, PRIMARY KEY (id));

