CREATE TABLE IF NOT EXISTS USERS (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), last_name VARCHAR(255), email VARCHAR(255), password VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS WALLETS (id INT NOT NULL AUTO_INCREMENT, user_id INT, nickname VARCHAR(255), balance INT, userId INT, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS TRANSACTIONS (id INT NOT NULL AUTO_INCREMENT, origin_wallet_id INT, target_wallet_id INT, amount LONG, created_at DATETIME, PRIMARY KEY (id));

